name: internet_originals
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  pinput: ^5.0.1
  image_picker: ^1.1.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/language/
    - assets/icons/profile/
    - assets/icons/personal_information/
    - assets/icons/social_platforms/
    - assets/icons/settings_security/
    - assets/icons/payments/
    - assets/icons/notification/
  
  fonts:
    - family: Open-Sans
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
